### ISSUE TITLE
Error when using pronouns custom 

### ISSUE THREAD

**Issue by rm20killer** [Simplexity-Development/SimplePronouns#1]
No errors on server console.
Client gets the error
`Command not found, please check your spelling and run the command again`

When doing `/pronouns custom`, I also tried `/simplepronouns:pronouns custom` to avoid any command conflicts
Filling in the args also does not work giving the same error

paper: 1.21.1-57
Plugin version: 1.0.1

**Comment by RhythmicSys** [comment]
Confirmed, able to reproduce. 
![image](https://github.com/user-attachments/assets/97aba335-3e01-4373-a239-5de6bb23e3bc)

**Comment by RhythmicSys** [comment]
Ah I see why I didn't catch this before, this specifically occurs when the config has been set to 'false' in 'allow custom pronouns' - which is a bit of a silly config option when I have a permission for custom pronouns anyways
https://modrinth.com/plugin/simple-pronouns/version/1.0.2
