### ISSUE TITLE
Unable to get the pronouns of an offline player

### ISSUE THREAD

**Issue by FaultyFunctions** [Simplexity-Development/SimplePronouns#2]
Hello I'm not sure if this is a bug or it's just not a feature but I cannot get the pronouns of offline players. I think this would be a super useful feature to have.

**Comment by RhythmicSys** [comment]
Falls under 'not currently a feature' but will add as a feature request!

**Comment by Peashooter101** [comment]
One more thing to note. To access the pronouns of an offline player, you must not be using the PDC saving type. We only grab the PersistentDataContainers (PDCs) if they are online. Currently the only other saving type for SimplePronouns is MySQL.

If you attempt to get the pronouns of that player, it will default to the default pronouns setting.

**Comment by FaultyFunctions** [comment]
Will changing the option from PDC to MySQL erase the data of our users or is it converted properly?

**Comment by RhythmicSys** [comment]
It would not be able to be converted, currently. It won't be *deleted* - technically, but it won't be accessible. 
A system can be added, but it will take a bit longer as the current saving system needs major overhaul before we can make changes to it

**Comment by FaultyFunctions** [comment]
Okay no worries I can wait for that no biggie. Should I make a separate suggestion for it?

**Comment by RhythmicSys** [comment]
That'd be good, thanks 😄

**Comment by Peashooter101** [comment]
@FaultyFunctions 

> Will changing the option from PDC to MySQL erase the data of our users or is it converted properly?

Added this in the commit shown above. This should work so long as the saving type is not PDC (so if we ever decide to add YML for example, you'd be able to do PDC to YML too). Will be available next update alongside the other fixes related to this issue.

> We only grab the PersistentDataContainers (PDCs) if they are online.

The original rationale for this was that we did not have access to the PDC data while the player was offline without doing some stuff that we did not want to do. Apparently, this was a recent addition to the Paper API that you can actually get the PDC of an offline player now for Minecraft 1.21.1+.

Honestly, I wish I noticed that before I made the push, but it's there now. Not that transferring PDC to MySQL will be that big of a deal anyway, but hey, that's cool!

**Comment by Peashooter101** [comment]
It did not occur to me that pasting the link to the PR would mark it on their side that I talked about it here. Also, fun fact, removing the link does not unlink that reference.

Sorry Paper. 😅

**Comment by RhythmicSys** [comment]
https://modrinth.com/plugin/simple-pronouns/version/2.0.0
Version is live on modrinth, note that the PAPI placeholders have changed due to having conflicts with another one of our plugins (oops lol) - the new placeholders are listed on the changelog
